name: CI/CD Pipeline

# Workflow wird bei jedem Push ausgelöst
on:
  push:
    branches:
      - '**'   # alle Branches

jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test  # Deploy wartet, bis Test abgeschlossen ist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Prepare public folder
        run: mv build public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages        # Branch für GitHub Pages
          folder: public          # Ordner, der deployed wird
          clean: true
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}