name: CI/CD Pipeline

# Workflow wird bei jedem Push ausgelöst
on:
  push:
    branches:
      - '**'   # alle Branches

jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # oder '20', Hauptsache >=20

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test  # Deploy wartet, bis Test abgeschlossen ist
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-
