name: Deploy Docusaurus

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Node.js einrichten
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: npm ci

      # 4. Docusaurus Seite bauen
      - name: Build Docusaurus site
        run: npm run build

      # 5. Deploy auf GitHub Pages via SSH
      - name: Deploy to GitHub Pages via SSH
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # hier den SSH-Schlüssel als Secret einfügen
