name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Prepare public folder
        run: mv build public

      - name: Deploy
  uses: JamesIves/github-pages-deploy-action@v4
  with:
    branch: gh-pages
    folder: public
    clean: true
    ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
