name: Docusaurus CI/CD

on:
  push:
    branches:
      - '**' # auf alle Branches reagieren
  pull_request:

jobs:
  test:
    name: Test (build check)
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' # nur auf Nicht-Main-Branches
    container: node:18-alpine3.20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # nur auf main-Branch
    container: node:18-alpine3.20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Docusaurus
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
